updated Jenkinfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -1,21 +1,75 @@
 pipeline {
-    agent {
-        docker {
-            image 'node:18'
-        }
+    agent any
+
+    environment {
+        IMAGE_NAME = "myapp"
+        REGISTRY = "docker.io/gomathidocker123"
     }
 
     stages {
-        stage('Install') {
+
+        stage('Checkout Code') {
+            steps {
+                git branch: 'main',
+                    url: 'https://github.com/gomathimanohar/CI-CD-pipeline.git'
+            }
+        }
+
+        stage('Install Dependencies') {
             steps {
                 sh 'npm install'
             }
         }
 
-        stage('Test') {
+        stage('Run Tests') {
             steps {
-                sh 'npm test'
+                sh 'npm test || true'
             }
+        }
+
+        stage('Build Docker Image') {
+            steps {
+                sh """
+                docker build -t $IMAGE_NAME .
+                """
+            }
+        }
+
+        stage('Tag Image') {
+            steps {
+                sh """
+                docker tag $IMAGE_NAME $REGISTRY/$IMAGE_NAME:latest
+                """
+            }
+        }
+
+        stage('Push Image') {
+            steps {
+                withDockerRegistry([credentialsId: 'dockerhub-creds', url: '']) {
+                    sh """
+                    docker push $REGISTRY/$IMAGE_NAME:latest
+                    """
+                }
+            }
+        }
+
+        stage('Deploy') {
+            steps {
+                sh """
+                docker stop myapp || true
+                docker rm myapp || true
+                docker run -d -p 3000:3000 --name myapp $REGISTRY/$IMAGE_NAME:latest
+                """
+            }
+        }
+    }
+
+    post {
+        success {
+            echo "Deployment Successful 🚀"
+        }
+        failure {
+            echo "Deployment Failed ❌"
         }
     }
 }
